package.json
yarn.lock

Closes #7, there are a bunch of earlier broken patches for this dependency.

Upgrade eslint-plugin-jest to 22.6.3

---

index.js
tests/config.test.js

BREAKING CHANGE: Updating to the new version (assuming this is merged) will cause significant changes in consumers of the package. Those changes should be cosmetic, but will still likely produce a significant number of changes
Based on discussions internally, a lot of PR comments were being posted about import sorting, or member sorting, and those are the types of bikeshedding we don't want to deal with. Even if we're not 100% happy with the results of the automatic sorting, it's better than having to add comments to every PR about sorting.

feat: enforce import sorting

---

index.js

Removes `require-atomic-updates`.
Information on the rule: https://eslint.org/docs/rules/require-atomic-updates
I propose removing `require-atomic-updates` as it produces too many false positives such that it can't be used reliably. If we can't rely on this rule correctly identifying problematic cases, it does more harm than good by creating confusion.
Discussion around the known issues: https://github.com/eslint/eslint/issues/11899
We should only re-enable this rule once it has been fixed in the official eslint repository.
---
Latest update from eslint, they're removing the rule in a minor release from eslint recommended: https://github.com/eslint/tsc-meetings/blob/master/notes/2019/2019-10-10.md#require-atomic-updates-false-positive

fix: remove buggy require-atomic-updates

---

README.md
base.js
index.js
tests/config.test.js

Moves the default config to a config called `base` and updates the default config to include `base`, `react`, and `jest`.
Definitely a breaking change.
Some guidance drawn from the much-lauded Airbnb config: https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb-base/index.js

feat: Add base config

---

base.js
index.js

This was initially moved in https://github.com/tophat/eslint-config/pull/38 when the base config was created. After playing around with the published version, I realized the prettier config specifies trailing commas everywhere, which mandates a minimum ecmaVersion of 9, so it makes sense to specify parserOptions in base config. RETURN HOME MY WAYWARD SON.
A BREAKING CHANGE, technically.

feat: Move parser options back to base config

---

base.js

I didn't try this one out, and I immediately hate it. Let's look at a few use cases why this sucks:
```js
export const selector1 = () => {}
const internal selector2 = () => {}
export const selector3 = state => { selector2(state).get('something_else') }
```
This is a really common pattern of "internal selectors" to help save some duplication for public selectors. In a small file it's fine to put at the top, but in a file of 50+ selectors it makes sense to colocate your internal selector with the selectors that use it.
```js
export class UnconnectedComponent {}
const mapStateToProps = {}
const mapDispatchToProps = {}
export default connect(unconnectedComponent)
```
This is a SUPER common example. To resolve this rule, we have to move `mapStateToProps` and `mapDispatchToProps` to the top …

feat: remove exports-last-rule

---

jest.js

When using redux saga test plan, these two patterns are common:
```javascript
it('does something', () => {
testSaga(mySaga).run()
})
it('does something', () => expectSaga(mySaga).run())
```
Currently this raises "Test has no assertion" warnings via `jest/expect-expect`. I'm proposing adding function name exceptions via: https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/expect-expect.md.

fix: don't fail jest expect when using redux test plan

---

base.js
tests/config.test.js

This rule complements the prettier quotes option by disallowing unnecessary template strings:
```js
// BAD:
const x = `dont need template here`
```
```js
// GOOD:
const x = 'nice, no template needed'
const y = `also ${1 + 1} ok bc I need template`
const z = `so okay
because i like
multilines baby`
```
Using template strings only when actual interpolation or multiline is needed makes it clearer what the code is doing: no backticks, no interpolation, just take the string for what it is. Otherwise it's not immediately clear whether or not a back-ticked string will have interpolation in it (especially for some longer strings), and therefore whether or not it can be moved around easily.

feat: Add quotes rule

---

base.js
package.json
tests/config.test.js
yarn.lock

See https://prettier.io/blog/2020/03/21/2.0.0.html for details. We are still compatible for the >= 1.0.0 range.

fix: Update config to support prettier@2

---

react.js

The rule `jsx-a11y/label-has-for` [was deprecated](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/master/docs/rules/label-has-for.md) and replaced by `jsx-a11y/label-has-associated-control` which is a more lenient version of the deprecated rule.
This will not cause any new errors because everything enforced by `label-has-associated-control` was already being enforced by `label-has-for`. Therefore it only requires a minor version bump

feat: delete deprecated rule and add replacement rule

---

base.js
tests/config.test.js

Based on a recent discussion about expanding support for typescript, always using parentheses on arrow functions would make adding type notations simpler.

feat: Always use arrow parens to make migration to typescript simpler

---

base/index.js
package.json
yarn.lock

If you use an array for the resolver, it will go in the specified order of the array. This moves our custom resolver (which works better with yarn 2) over the default node resolver. 
Also updates the peer dependency on our custom resolver to the version that handles virtual sibling packages correctly.

fix: specify to use custom tophat resolver before node

---

base/index.js

`@typescript-eslint/no-extra-semi` conflicts with prettiers opinion on how/where semi colons should be placed. For example, this is irreconcilable:
```js
;(async () => {
return 1
})().then((code) => process.exit(code))
```
prettier insists that a semi-colon is present, and @typescript-eslint/no-extra-semi insists one is not. If you have formatting on save set up, you will actually see each one win on every other save.
Prettier provides a configuration to turn off all the rules it disagrees with, which we use, but that config **must** be the last item in the list, to ensure all the previous rules are turned off correctly. When we added typescript support, it was added below the prettier config. This restores the correct order and should prevent the problem.

fix: Prevent tslint and prettier from fighting over semi-colons

---

base/index.js

Functions can still be used before they are defined, the issue is largely with variables and classes not in ES6.

fix: Exclude functions from no-use-before-define rule

---

base/index.js
package.json
yarn.lock

BREAKING CHANGE: You will need to run `eslint --fix .` on your code base when adopting this update and it will sort all imports in your codebase. After this change, there will be a single correct order for all imports with an auto-fixing rule to correct them.
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/order.md#alphabetize-order-ascdescignore-caseinsensitive-truefalse

feat: Alphabetize imports by import location

---

react/index.js

https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/require-default-props.md#functions
So we can use function defaults instead of requiring the static defaultProps.

feat(react): use default arguments for function components

---

README.md

We made changes to be more optional about the react dependencies, but forgot to update documentation.

docs: Update documentation that react packages are optional

---

react/index.js

We have the jsx-a11y plugin installed but don't use very much of it. They have recommended and strict rulesets that we can extend, and we for some reason just never did.
Note that adopting this may be hard since we probably fail a bunch of these in a bunch of places. My suggestion is that we attempt to adopt the change, then turn any failing rules to 'warn' level in that repo.

feat: Enforce stricter a11y rules

---

.eslintrc.js
base/index.js
tests/config.test.js
tests/example.js
tsconfig.json

BREAKING CHANGE: We are expanding your list of typescript rules which requires connecting your eslint config to your tsconfig. See the typescript-eslint documentation https://typescript-eslint.io/linting/typed-linting for how to do this. If your project does not use typescript and you do not want to add a tsconfig file needlessly, disable the following rules in your config: @typescript-eslint/no-confusing-void-expression, @typescript-eslint/no-for-in-array, @typescript-eslint/prefer-includes, @typescript-eslint/prefer-reduce-type-parameter, and @typescript-eslint/prefer-string-starts-ends-with.

feat: Expand list of typescript rules

---

react/index.js

In TypeScript components, we know with certainty when a condition might shortcircuit and return undefined and thus cause React to crash.
From the docs for the rule https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-no-leaked-render.md#when-not-to-use-it:
> When Not To Use It
> If you are working in a typed-codebase which encourages you to always use boolean conditions, this rule can be disabled.

fix: disable react/jsx-no-leaked-render in TypeScript components

---

src/react/index.ts

BREAKING CHANGE: Since we are setting the @tanstack/query/prefer-query-object-syntax, this will require changes to your code that satisfy the rule before CI will pass. You will no longer be able to skip these changes.
--- 
This PR adopts the recommended config for tanstack eslint-plugin-query. The recommended config configures all rules in eslint-plugin-query as errors. In particular, we are now requiring object syntax by setting the `"@tanstack/query/prefer-query-object-syntax"` rule to `error`. `@tanstack/query/exhaustive-deps` was already set to error.

feat: adopt recommended config for tanstack eslint-plugin-query

---

plugins/eslint-plugin-import/src/index.ts
plugins/eslint-plugin-import/src/rules/prefer-non-default-react-imports/README.md
plugins/eslint-plugin-import/src/rules/prefer-non-default-react-imports/index.ts
plugins/eslint-plugin-import/src/rules/prefer-non-default-react-imports/prefer-named-react-import.test.ts

This rule prefers `useState` syntax over `React.useState` syntax. It is auto-fixable.
In your `.eslintrc.js` file:
```js
module.exports = {
extends: ['plugin:@tophat/eslint-plugin-import/recommended'],
plugins: ['@tophat/eslint-plugin-import'],
rules: {
'@tophat/import/prefer-non-default-react-imports': 'error',
},
}
```
```js
import React, { useEffect } from 'react'
function Component() {
useEffect(() => {}, [])
}
```
```js
import React from 'react'
function Component() {
React.useEffect(() => {}, [])
}
```
You can override the default list of methods by setting `methods`:
```js
module.exports = {
extends: ['plugin:@tophat/eslint-plugin-import/recommended'],
plugins: ['@tophat/eslint-plugin-import'],
rules: {
'@tophat/import/prefer-non-default-react-imports': ['error', { methods: …
```

feat: add prefer-non-default-react-imports rule

---

.github/workflows/cicd.yml
.yarn/sdks/typescript/package.json
config/package.json
package.json
yarn.lock

This raises the peer dependency version for typescript from 4.9.5 to 5.0.4. We can _probably_ not do that, but I think it makes sense to require typescript no more than 1 version back for this library.

deps: Update typescript, yarn, and monodeploy to latest

---

config/src/base/index.ts

The `no-confusing-void-expression` is causing some issues with certain ambiguous type declarations. If unaware, the auto linting may add `void` to method calls where we are expecting a return value. Since linter fixes should always be safe (no code behaviour changes), I've turned off the rule.

fix: ignore no-confusing-void-expression as it changes code behaviour

---

config/src/base/index.ts

Removed the `no-confusing-void-expression` rule as the default is already `off`.

fix: removed no-confusing-void-expressions rule

---

config/src/base/index.ts

NOTE: Disable @typescript-eslint/consistent-indexed-object-style and @typescript-eslint/class-literal-property-style

fix: disable rules to ease v9 migration
